name: Auto PR from dev to main

on:
  push:
    branches:
      - dev  # Trigger only when changes are pushed to dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          base: main
          title: 'Auto PR from dev to main'
          body: 'This PR is automatically created when changes are pushed to the dev branch.'

      - name: Show PR details
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          echo "Pull Request Number: ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
