name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Show GH CLI version (debug)
        run: gh --version

      - name: Create Pull Request

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "Auto PR: dev to main" \
            --body "This PR was automatically created."\
            --label "QA"

