name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  raise-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Create PR from dev to main
        if: steps.check.outputs.pr_exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "Auto PR: dev → main" \
            --body "This pull request was automatically created when changes were pushed to dev."
