name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to see all branches

      - name: Debug branches
        run: |
          echo "Current ref: ${{ github.ref }}"
          git branch -a
          git log --oneline -n 3

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Dev Updates - ${{ github.sha }}"
          body: "Automated PR from dev branch\nCommit: ${{ github.sha }}"
          base: main
          head: dev
          draft: false
          assignees: ${{ github.actor }}
          labels: "automated"

      - name: Show PR result
        if: always()
        run: |
          echo "PR creation status: ${{ steps.create-pr.outputs.result }}"
          echo "PR number: ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "PR URL: ${{ steps.create-pr.outputs.pull-request-url }}"
