name: Create PR from dev to main

on:
  push:
    branches:
      - dev  # Only triggers on pushes to dev branch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Updates from dev branch"
          body: "Automated PR containing latest changes from dev"
          base: main
          branch: dev  # Correct input name
          draft: false
          assignees: ${{ github.actor }}
          labels: "automated-pr"
